// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.gear")]
public sealed class GearAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "GEAR";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_GEAR_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.flaps_up")]
public sealed class FlapsUpAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FLP+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FLAPS_UP_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.flaps_down")]
public sealed class FlapsDownAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FLP-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FLAPS_DOWN_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.airbrake")]
public sealed class AirbrakeAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "AIRB";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_AIR_BRAKE_HELICOPTER");
}
