// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.gear")]
public sealed class GearAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "GEAR";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_GEAR_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.flaps_up")]
public sealed class FlapsUpAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FLP+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FLAPS_UP_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.flaps_down")]
public sealed class FlapsDownAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FLP-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FLAPS_DOWN_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.airbrake")]
public sealed class AirbrakeAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "AIRB";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_AIR_BRAKE_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.coll_max")]
public sealed class CollMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "COL+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_collective_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.coll_min")]
public sealed class CollMinAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "COL-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_collective_rangeMin");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.pedal_max")]
public sealed class PedalMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "PED>";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_pedals_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.pedal_min")]
public sealed class PedalMinAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "<PED";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_pedals_rangeMin");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.cpitch_max")]
public sealed class CpitchMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "PIT+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_cyclic_pitch_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.cpitch_min")]
public sealed class CpitchMinAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "PIT-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_cyclic_pitch_rangeMin");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.croll_max")]
public sealed class CrollMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ROL+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_cyclic_roll_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.mech.croll_min")]
public sealed class CrollMinAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ROL-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_cyclic_roll_rangeMin");
}
