// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
using SharpDeck;

namespace WarThunderStreamDeckPlugin;

internal static class Program
{
    public static Task Main() => StreamDeckPlugin.RunAsync();
}
