// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.heli.sensors.night_vision")]
public sealed class NightVisionAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "NV";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_HELI_GUNNER_NIGHT_VISION");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.sensors.seeker_cam")]
public sealed class SeekerCamAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SKR";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_CAMERA_SEEKER_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.sensors.sensor_switch")]
public sealed class SensorSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SNS";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_SWITCH_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.sensors.sensor_lock")]
public sealed class SensorLockAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LOCK";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_TARGET_LOCK_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.sensors.laser")]
public sealed class LaserAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LASER";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_LASER_DESIGNATOR_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.sensors.tgt_cam")]
public sealed class TgtCamAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "TGTC";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TARGET_CAMERA_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.sensors.lock_pt")]
public sealed class LockPtAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LKPT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_LOCK_TARGETING_AT_POINT_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.sensors.cue_x_max")]
public sealed class CueXMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUX+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_sensor_cue_x_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.sensors.cue_x_min")]
public sealed class CueXMinAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUX-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_sensor_cue_x_rangeMin");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.sensors.cue_y_max")]
public sealed class CueYMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUY+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_sensor_cue_y_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.sensors.cue_y_min")]
public sealed class CueYMinAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUY-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "helicopter_sensor_cue_y_rangeMin");
}
