// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.mechanisation.air_reverse")]
public sealed class AirReverseAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "REV";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_AIR_REVERSE");
}

[StreamDeckAction("com.blacksiroghost.wt.mechanisation.bay_door")]
public sealed class BayDoorAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "BAY";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_BAY_DOOR");
}

[StreamDeckAction("com.blacksiroghost.wt.mechanisation.cockpit_door")]
public sealed class CockpitDoorAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CKPT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_COCKPIT_DOOR");
}

[StreamDeckAction("com.blacksiroghost.wt.mechanisation.trans_gear")]
public sealed class TransGearAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "HOOK";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TRANS_GEAR_DOWN");
}

[StreamDeckAction("com.blacksiroghost.wt.mechanisation.boosters")]
public sealed class BoostersAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "WEP";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_IGNITE_BOOSTERS");
}

[StreamDeckAction("com.blacksiroghost.wt.mechanisation.vtol_up")]
public sealed class VtolUpAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "VTOL+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "vtol_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.mechanisation.vtol_down")]
public sealed class VtolDownAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "VTOL-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "vtol_rangeMin");
}
