// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.view.toggle")]
public sealed class ToggleAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "VIEW";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_VIEW");
}

[StreamDeckAction("com.blacksiroghost.wt.view.toggle_heli")]
public sealed class ToggleHeliAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "HVW";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_VIEW_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.view.neutral")]
public sealed class NeutralAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CTR";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_CAMERA_NEUTRAL");
}

[StreamDeckAction("com.blacksiroghost.wt.view.view_down")]
public sealed class ViewDownAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "DOWN";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_CAMERA_VIEW_DOWN");
}

[StreamDeckAction("com.blacksiroghost.wt.view.driver")]
public sealed class DriverAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "DRV";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_CAMERA_DRIVER");
}

[StreamDeckAction("com.blacksiroghost.wt.view.binoc")]
public sealed class BinocAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "BINO";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_CAMERA_BINOCULARS");
}

[StreamDeckAction("com.blacksiroghost.wt.view.tgt_cam")]
public sealed class TgtCamAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "TGT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TARGET_CAMERA");
}

[StreamDeckAction("com.blacksiroghost.wt.view.uav")]
public sealed class UavAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "UAV";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_UAV_CAMERA");
}

[StreamDeckAction("com.blacksiroghost.wt.view.cam_x")]
public sealed class CamXAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CAMX";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "camx_rangeSet");
}

[StreamDeckAction("com.blacksiroghost.wt.view.cam_y")]
public sealed class CamYAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CAMY";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "camy_rangeSet");
}
