// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.ship.combat.lock_pt")]
public sealed class LockPtAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LKPT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_LOCK_TARGETING_AT_POINT_SHIP");
}

[StreamDeckAction("com.blacksiroghost.wt.ship.combat.zoom_max")]
public sealed class ZoomMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ZOOM+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ship_zoom_rangeMax");
}
