// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.weapons.aa.aam")]
public sealed class AamAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "AAM";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_AAM");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.aa.fire_primary")]
public sealed class FirePrimaryAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FIRE1";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_PRIMARY");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.aa.fire_secondary")]
public sealed class FireSecondaryAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FIRE2";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_SECONDARY");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.aa.fire_cannons")]
public sealed class FireCannonsAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CANN";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_CANNONS");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.aa.fire_mguns")]
public sealed class FireMgunsAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "MGUN";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_MGUNS");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.aa.fire_add_guns")]
public sealed class FireAddGunsAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ADDG";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_ADDITIONAL_GUNS");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.aa.lock_target")]
public sealed class LockTargetAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LOCK";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_LOCK_TARGET");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.aa.weapon_lock")]
public sealed class WeaponLockAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "WLCK";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_WEAPON_LOCK");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.aa.cycle_primary")]
public sealed class CyclePrimaryAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CYC1";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SWITCH_SHOOTING_CYCLE_PRIMARY");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.aa.cycle_secondary")]
public sealed class CycleSecondaryAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CYC2";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SWITCH_SHOOTING_CYCLE_SECONDARY");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.aa.reload")]
public sealed class ReloadAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RELD";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_RELOAD_GUNS");
}
