// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.agm")]
public sealed class AgmAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "AGM";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_AGM");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.agm_lock")]
public sealed class AgmLockAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "AGML";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_AGM_LOCK");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.atgm")]
public sealed class AtgmAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ATGM";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ATGM");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.bombs")]
public sealed class BombsAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "BOMB";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_BOMBS");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.bombs_series")]
public sealed class BombsSeriesAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "BMB^";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_BOMBS_SERIES");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.rockets")]
public sealed class RocketsAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ROCK";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ROCKETS");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.rockets_series")]
public sealed class RocketsSeriesAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ROK^";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ROCKETS_SERIES");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.gbu_drop")]
public sealed class GbuDropAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "GBU";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_GUIDED_BOMBS");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.gbu_lock")]
public sealed class GbuLockAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "GBUL";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_GUIDED_BOMBS_LOCK");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.laser")]
public sealed class LaserAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LASER";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_LASER_DESIGNATOR");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.rocket_bc")]
public sealed class RocketBcAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RBC";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_ROCKETS_BALLISTIC_COMPUTER");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.bc")]
public sealed class BcAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "BC";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_CANNONS_AND_ROCKETS_BALLISTIC_COMPUTER");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.designate")]
public sealed class DesignateAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "DSGN";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_DESIGNATE_TARGET");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.lock_pt")]
public sealed class LockPtAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LKPT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_LOCK_TARGETING_AT_POINT");
}

[StreamDeckAction("com.blacksiroghost.wt.weapons.ag.unlock_pt")]
public sealed class UnlockPtAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ULPT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_UNLOCK_TARGETING_AT_POINT");
}
