// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.fire_primary")]
public sealed class FirePrimaryAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FIRE1";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_PRIMARY_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.fire_secondary")]
public sealed class FireSecondaryAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FIRE2";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_SECONDARY_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.fire_mguns")]
public sealed class FireMgunsAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "MGUN";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_MGUNS_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.fire_cannons")]
public sealed class FireCannonsAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CANN";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_CANNONS_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.fire_add_guns")]
public sealed class FireAddGunsAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ADDG";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_ADDITIONAL_GUNS_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.flares")]
public sealed class FlaresAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FLR";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FLARES_SERIES_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.rocket_bc")]
public sealed class RocketBcAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RBC";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_ROCKETS_BALLISTIC_COMPUTER_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.bc")]
public sealed class BcAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "BC";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_CANNONS_AND_ROCKETS_BALLISTIC_COMPUTER_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.cycle_primary")]
public sealed class CyclePrimaryAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CYC1";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SWITCH_SHOOTING_CYCLE_PRIMARY_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.cycle_secondary")]
public sealed class CycleSecondaryAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CYC2";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SWITCH_SHOOTING_CYCLE_SECONDARY_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.instructor")]
public sealed class InstructorAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "INST";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_INSTRUCTOR_HELICOPTER");
}

[StreamDeckAction("com.blacksiroghost.wt.heli.combat.exit_cycle")]
public sealed class ExitCycleAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "EXIT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_EXIT_SHOOTING_CYCLE_MODE_HELICOPTER");
}
