// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.tank.movement.dir_drive")]
public sealed class DirDriveAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "DRV";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ENABLE_GM_DIRECTION_DRIVING");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.movement.susp_clr_up")]
public sealed class SuspClrUpAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SUSP+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SUSPENSION_CLEARANCE_UP");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.movement.susp_clr_dn")]
public sealed class SuspClrDnAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SUSP-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SUSPENSION_CLEARANCE_DOWN");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.movement.susp_pit_up")]
public sealed class SuspPitUpAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "PIT+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SUSPENSION_PITCH_UP");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.movement.susp_pit_dn")]
public sealed class SuspPitDnAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "PIT-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SUSPENSION_PITCH_DOWN");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.movement.susp_rol_up")]
public sealed class SuspRolUpAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ROL>";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SUSPENSION_ROLL_UP");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.movement.susp_rol_dn")]
public sealed class SuspRolDnAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "<ROL";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SUSPENSION_ROLL_DOWN");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.movement.susp_reset")]
public sealed class SuspResetAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RST";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SUSPENSION_RESET");
}
