// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.engine.throttle_max")]
public sealed class ThrottleMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "THR+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "throttle_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.engine.throttle_min")]
public sealed class ThrottleMinAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "IDLE";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "throttle_rangeMin");
}

[StreamDeckAction("com.blacksiroghost.wt.engine.manuv_mode")]
public sealed class ManuvModeAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "MANUV";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_MANEUVERABILITY_MODE");
}
