// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.radar.air.sensor_switch")]
public sealed class SensorSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RDR";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_SWITCH");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.air.mode_switch")]
public sealed class ModeSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "MODE";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_MODE_SWITCH");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.air.range_switch")]
public sealed class RangeSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RNG";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_RANGE_SWITCH");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.air.scan_switch")]
public sealed class ScanSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SCAN";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_SCAN_PATTERN_SWITCH");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.air.acm")]
public sealed class AcmAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ACM";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_ACM_SWITCH");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.air.target_lock")]
public sealed class TargetLockAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LOCK";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_TARGET_LOCK", "ID_LOCK_TARGET", "ID_LOCK_TARGETING");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.air.target_switch")]
public sealed class TargetSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "TGT>";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_TARGET_SWITCH");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.air.type_switch")]
public sealed class TypeSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "TYPE";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_TYPE_SWITCH");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.air.lock_des")]
public sealed class LockDesAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LCKD";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_LOCK_TARGETING");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.air.unlock_des")]
public sealed class UnlockDesAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ULDD";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_UNLOCK_TARGETING");
}
