// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.optics.air.thermal")]
public sealed class ThermalAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "THM";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_THERMAL_WHITE_IS_HOT");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.night_vision")]
public sealed class NightVisionAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "NV";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_PLANE_NIGHT_VISION");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.designate")]
public sealed class DesignateAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "DSGN";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_DESIGNATE_TARGET");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.lock_pt")]
public sealed class LockPtAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LKPT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_LOCK_TARGETING_AT_POINT");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.cue_x_max")]
public sealed class CueXMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUEX+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "sensor_cue_x_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.cue_x_min")]
public sealed class CueXMinAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUEX-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "sensor_cue_x_rangeMin");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.cue_x_set")]
public sealed class CueXSetAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUEX0";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "sensor_cue_x_rangeSet");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.cue_y_max")]
public sealed class CueYMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUEY+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "sensor_cue_y_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.cue_y_min")]
public sealed class CueYMinAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUEY-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "sensor_cue_y_rangeMin");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.cue_y_set")]
public sealed class CueYSetAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUEY0";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "sensor_cue_y_rangeSet");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.cue_z_max")]
public sealed class CueZMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUEZ+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "sensor_cue_z_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.cue_z_min")]
public sealed class CueZMinAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUEZ-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "sensor_cue_z_rangeMin");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.cue_z_set")]
public sealed class CueZSetAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CUEZ0";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "sensor_cue_z_rangeSet");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.laser")]
public sealed class LaserAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LASER";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_LASER_DESIGNATOR");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.tgt_cam")]
public sealed class TgtCamAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "TGTC";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TARGET_CAMERA");
}

[StreamDeckAction("com.blacksiroghost.wt.optics.air.uav_cam")]
public sealed class UavCamAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "UAV";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_UAV_CAMERA");
}
