// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.tank.combat.fire_secondary")]
public sealed class FireSecondaryAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FIRE2";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_GM_SECONDARY_GUN");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.combat.fire_special")]
public sealed class FireSpecialAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SPEC";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FIRE_GM_SPECIAL_GUN");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.combat.sel_primary")]
public sealed class SelPrimaryAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "G1";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SELECT_GM_GUN_PRIMARY");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.combat.sel_secondary")]
public sealed class SelSecondaryAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "G2";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SELECT_GM_GUN_SECONDARY");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.combat.sel_mg")]
public sealed class SelMgAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "MG";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SELECT_GM_GUN_MACHINEGUN");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.combat.sel_reset")]
public sealed class SelResetAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RST";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SELECT_GM_GUN_RESET");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.combat.smoke")]
public sealed class SmokeAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SMK";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SMOKE_SCREEN_GENERATOR");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.combat.repair")]
public sealed class RepairAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RPR";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_REPAIR_TANK");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.combat.hull_aim")]
public sealed class HullAimAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "HULL";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ENABLE_GM_HULL_AIMING");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.combat.reload")]
public sealed class ReloadAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RELD";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_RELOAD_GUNS");
}
