// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.radar.ground.sensor_switch")]
public sealed class SensorSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RDR";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_SWITCH_TANK");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.ground.mode_switch")]
public sealed class ModeSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "MODE";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_MODE_SWITCH_TANK");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.ground.range_switch")]
public sealed class RangeSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RNG";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_RANGE_SWITCH_TANK");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.ground.scan_switch")]
public sealed class ScanSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SCAN";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_SCAN_PATTERN_SWITCH_TANK");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.ground.target_lock")]
public sealed class TargetLockAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "LOCK";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_TARGET_LOCK_TANK");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.ground.target_switch")]
public sealed class TargetSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "TGT>";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_TARGET_SWITCH_TANK");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.ground.view_switch")]
public sealed class ViewSwitchAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "VIEW";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SENSOR_VIEW_SWITCH_TANK");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.ground.weapon_lock")]
public sealed class WeaponLockAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "WLCK";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_WEAPON_LOCK_TANK");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.ground.ircm")]
public sealed class IrcmAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "IRCM";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_IRCM_SWITCH_TANK");
}

[StreamDeckAction("com.blacksiroghost.wt.radar.ground.aps_lock")]
public sealed class ApsLockAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "APS";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_LOCK_TARGETING_AT_POINT_SHIP");
}
