// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.coms.voice1")]
public sealed class Voice1Action : WarThunderBindingAction
{
    protected override string TitlePrefix => "V1";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_VOICE_MESSAGE_1");
}

[StreamDeckAction("com.blacksiroghost.wt.coms.voice2")]
public sealed class Voice2Action : WarThunderBindingAction
{
    protected override string TitlePrefix => "V2";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_VOICE_MESSAGE_2");
}

[StreamDeckAction("com.blacksiroghost.wt.coms.voice5")]
public sealed class Voice5Action : WarThunderBindingAction
{
    protected override string TitlePrefix => "V5";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_VOICE_MESSAGE_5");
}

[StreamDeckAction("com.blacksiroghost.wt.coms.voice7")]
public sealed class Voice7Action : WarThunderBindingAction
{
    protected override string TitlePrefix => "V7";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_VOICE_MESSAGE_7");
}

[StreamDeckAction("com.blacksiroghost.wt.coms.voice8")]
public sealed class Voice8Action : WarThunderBindingAction
{
    protected override string TitlePrefix => "V8";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_VOICE_MESSAGE_8");
}

[StreamDeckAction("com.blacksiroghost.wt.coms.ptt")]
public sealed class PttAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "PTT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_PTT");
}

[StreamDeckAction("com.blacksiroghost.wt.coms.voice_squad")]
public sealed class VoiceSquadAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SQDV";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SHOW_VOICE_MESSAGE_LIST_SQUAD");
}

[StreamDeckAction("com.blacksiroghost.wt.coms.squad_des")]
public sealed class SquadDesAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SQDD";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SQUAD_TARGET_DESIGNATION");
}

[StreamDeckAction("com.blacksiroghost.wt.coms.support")]
public sealed class SupportAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SUPP";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_START_SUPPORT_PLANE");
}

[StreamDeckAction("com.blacksiroghost.wt.coms.orbit")]
public sealed class OrbitAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ORB";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SUPPORT_PLANE_ORBITING");
}

[StreamDeckAction("com.blacksiroghost.wt.coms.wheel")]
public sealed class WheelAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "WHEEL";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SHOW_MULTIFUNC_WHEEL_MENU");
}
