using System;

namespace WarThunderStreamDeckPlugin.KeyBindings
{
    // Plain POCO: only auto-properties. Filled by a separate loader.
    public sealed class KeyBindings
    {
        // Hotkeys (IDs)
        public string? ID_AAM { get; set; }
        public string? ID_ACTION_BAR_ITEM_5 { get; set; }
        public string? ID_ACTION_BAR_ITEM_6 { get; set; }
        public string? ID_ACTION_BAR_ITEM_7 { get; set; }
        public string? ID_ACTION_BAR_ITEM_8 { get; set; }
        public string? ID_ACTION_BAR_ITEM_9 { get; set; }
        public string? ID_AGM { get; set; }
        public string? ID_AGM_LOCK { get; set; }
        public string? ID_AIR_BRAKE { get; set; }
        public string? ID_AIR_BRAKE_HELICOPTER { get; set; }
        public string? ID_AIR_REVERSE { get; set; }
        public string? ID_ATGM { get; set; }
        public string? ID_BAY_DOOR { get; set; }
        public string? ID_BOMBS { get; set; }
        public string? ID_BOMBS_SERIES { get; set; }
        public string? ID_CAMERA_BINOCULARS { get; set; }
        public string? ID_CAMERA_DRIVER { get; set; }
        public string? ID_CAMERA_NEUTRAL { get; set; }
        public string? ID_CAMERA_SEEKER_HELICOPTER { get; set; }
        public string? ID_CAMERA_VIEW_DOWN { get; set; }
        public string? ID_CHANGE_SHOT_FREQ { get; set; }
        public string? ID_CONTINUE { get; set; }
        public string? ID_CONTROL_MODE { get; set; }
        public string? ID_DESIGNATE_TARGET { get; set; }
        public string? ID_ENABLE_GM_DIRECTION_DRIVING { get; set; }
        public string? ID_ENABLE_GM_HULL_AIMING { get; set; }
        public string? ID_EXIT_SHOOTING_CYCLE_MODE { get; set; }
        public string? ID_EXIT_SHOOTING_CYCLE_MODE_HELICOPTER { get; set; }
        public string? ID_FIRE_ADDITIONAL_GUNS { get; set; }
        public string? ID_FIRE_ADDITIONAL_GUNS_HELICOPTER { get; set; }
        public string? ID_FIRE_CANNONS { get; set; }
        public string? ID_FIRE_CANNONS_HELICOPTER { get; set; }
        public string? ID_FIRE_GM_SECONDARY_GUN { get; set; }
        public string? ID_FIRE_GM_SPECIAL_GUN { get; set; }
        public string? ID_FIRE_MGUNS { get; set; }
        public string? ID_FIRE_MGUNS_HELICOPTER { get; set; }
        public string? ID_FIRE_PRIMARY { get; set; }
        public string? ID_FIRE_PRIMARY_HELICOPTER { get; set; }
        public string? ID_FIRE_SECONDARY { get; set; }
        public string? ID_FIRE_SECONDARY_HELICOPTER { get; set; }
        public string? ID_FLAPS { get; set; }
        public string? ID_FLAPS_DOWN { get; set; }
        public string? ID_FLAPS_DOWN_HELICOPTER { get; set; }
        public string? ID_FLAPS_UP { get; set; }
        public string? ID_FLAPS_UP_HELICOPTER { get; set; }
        public string? ID_FLARES { get; set; }
        public string? ID_FLARES_SERIES_HELICOPTER { get; set; }
        public string? ID_FLIGHTMENU { get; set; }
        public string? ID_FLIGHTMENU_SETUP { get; set; }
        public string? ID_GAME_PAUSE { get; set; }
        public string? ID_GEAR { get; set; }
        public string? ID_GEAR_HELICOPTER { get; set; }
        public string? ID_GUIDED_BOMBS_LOCK { get; set; }
        public string? ID_HELI_GUNNER_NIGHT_VISION { get; set; }
        public string? ID_HIDE_HUD { get; set; }
        public string? ID_IGNITE_BOOSTERS { get; set; }
        public string? ID_IRCM_SWITCH_TANK { get; set; }
        public string? ID_IR_PROJECTOR { get; set; }
        public string? ID_LOCK_TARGET { get; set; }
        public string? ID_LOCK_TARGETING { get; set; }
        public string? ID_LOCK_TARGETING_AT_POINT { get; set; }
        public string? ID_LOCK_TARGETING_AT_POINT_HELICOPTER { get; set; }
        public string? ID_LOCK_TARGETING_AT_POINT_SHIP { get; set; }
        public string? ID_MANEUVERABILITY_MODE { get; set; }
        public string? ID_MPSTATSCREEN { get; set; }
        public string? ID_PLANE_NIGHT_VISION { get; set; }
        public string? ID_PTT { get; set; }
        public string? ID_RANGEFINDER { get; set; }
        public string? ID_RELOAD_GUNS { get; set; }
        public string? ID_REPAIR_TANK { get; set; }
        public string? ID_ROCKETS { get; set; }
        public string? ID_SCREENSHOT { get; set; }
        public string? ID_SELECT_GM_GUN_MACHINEGUN { get; set; }
        public string? ID_SELECT_GM_GUN_PRIMARY { get; set; }
        public string? ID_SELECT_GM_GUN_RESET { get; set; }
        public string? ID_SELECT_GM_GUN_SECONDARY { get; set; }
        public string? ID_SENSOR_ACM_SWITCH { get; set; }
        public string? ID_SENSOR_MODE_SWITCH { get; set; }
        public string? ID_SENSOR_MODE_SWITCH_TANK { get; set; }
        public string? ID_SENSOR_RANGE_SWITCH { get; set; }
        public string? ID_SENSOR_RANGE_SWITCH_TANK { get; set; }
        public string? ID_SENSOR_SCAN_PATTERN_SWITCH { get; set; }
        public string? ID_SENSOR_SCAN_PATTERN_SWITCH_TANK { get; set; }
        public string? ID_SENSOR_SWITCH { get; set; }
        public string? ID_SENSOR_SWITCH_HELICOPTER { get; set; }
        public string? ID_SENSOR_SWITCH_TANK { get; set; }
        public string? ID_SENSOR_TARGET_LOCK { get; set; }
        public string? ID_SENSOR_TARGET_LOCK_HELICOPTER { get; set; }
        public string? ID_SENSOR_TARGET_LOCK_TANK { get; set; }
        public string? ID_SENSOR_TARGET_SWITCH { get; set; }
        public string? ID_SENSOR_TARGET_SWITCH_TANK { get; set; }
        public string? ID_SENSOR_TYPE_SWITCH { get; set; }
        public string? ID_SENSOR_VIEW_SWITCH_TANK { get; set; }
        public string? ID_SHOW_MULTIFUNC_WHEEL_MENU { get; set; }
        public string? ID_SHOW_VOICE_MESSAGE_LIST_SQUAD { get; set; }
        public string? ID_SMOKE_SCREEN { get; set; }
        public string? ID_SMOKE_SCREEN_GENERATOR { get; set; }
        public string? ID_SQUAD_TARGET_DESIGNATION { get; set; }
        public string? ID_START_SUPPORT_PLANE { get; set; }
        public string? ID_SUPPORT_PLANE_ORBITING { get; set; }
        public string? ID_SUSPENSION_CLEARANCE_DOWN { get; set; }
        public string? ID_SUSPENSION_CLEARANCE_UP { get; set; }
        public string? ID_SUSPENSION_PITCH_DOWN { get; set; }
        public string? ID_SUSPENSION_PITCH_UP { get; set; }
        public string? ID_SUSPENSION_RESET { get; set; }
        public string? ID_SUSPENSION_ROLL_DOWN { get; set; }
        public string? ID_SUSPENSION_ROLL_UP { get; set; }
        public string? ID_SWITCH_SHOOTING_CYCLE_PRIMARY { get; set; }
        public string? ID_SWITCH_SHOOTING_CYCLE_PRIMARY_HELICOPTER { get; set; }
        public string? ID_SWITCH_SHOOTING_CYCLE_SECONDARY { get; set; }
        public string? ID_SWITCH_SHOOTING_CYCLE_SECONDARY_HELICOPTER { get; set; }
        public string? ID_TANK_NIGHT_VISION { get; set; }
        public string? ID_TANK_SWITCH_FUSE_MODE { get; set; }
        public string? ID_TARGETING_HOLD_GM { get; set; }
        public string? ID_TARGET_CAMERA { get; set; }
        public string? ID_TARGET_CAMERA_HELICOPTER { get; set; }
        public string? ID_THERMAL_WHITE_IS_HOT { get; set; }
        public string? ID_TOGGLE_CANNONS_AND_ROCKETS_BALLISTIC_COMPUTER { get; set; }
        public string? ID_TOGGLE_CANNONS_AND_ROCKETS_BALLISTIC_COMPUTER_HELICOPTER { get; set; }
        public string? ID_TOGGLE_COCKPIT_DOOR { get; set; }
        public string? ID_TOGGLE_GM_CROSSHAIR_LIGHTING { get; set; }
        public string? ID_TOGGLE_INSTRUCTOR { get; set; }
        public string? ID_TOGGLE_INSTRUCTOR_HELICOPTER { get; set; }
        public string? ID_TOGGLE_LASER_DESIGNATOR { get; set; }
        public string? ID_TOGGLE_LASER_DESIGNATOR_HELICOPTER { get; set; }
        public string? ID_TOGGLE_ROCKETS_BALLISTIC_COMPUTER { get; set; }
        public string? ID_TOGGLE_ROCKETS_BALLISTIC_COMPUTER_HELICOPTER { get; set; }
        public string? ID_TOGGLE_UAV_CAMERA { get; set; }
        public string? ID_TOGGLE_VIEW { get; set; }
        public string? ID_TOGGLE_VIEW_HELICOPTER { get; set; }
        public string? ID_TRANS_GEAR_DOWN { get; set; }
        public string? ID_UNLOCK_TARGETING { get; set; }
        public string? ID_UNLOCK_TARGETING_AT_POINT { get; set; }
        public string? ID_VOICE_MESSAGE_2 { get; set; }
        public string? ID_VOICE_MESSAGE_7 { get; set; }
        public string? ID_WEAPON_LOCK { get; set; }
        public string? ID_WEAPON_LOCK_TANK { get; set; }
        public string? ID_ZOOM_HOLD_GM { get; set; }
        public string? ID_ZOOM_TOGGLE { get; set; }

        // Range controls
        public string? ailerons_rangeMax { get; set; }
        public string? ailerons_rangeMin { get; set; }
        public string? brake_left_rangeMax { get; set; }
        public string? brake_right_rangeMax { get; set; }
        public string? camx_rangeSet { get; set; }
        public string? camy_rangeSet { get; set; }
        public string? elevator_rangeMax { get; set; }
        public string? elevator_rangeMin { get; set; }
        public string? fire_rangeMax { get; set; }
        public string? gm_sight_distance_rangeMax { get; set; }
        public string? gm_sight_distance_rangeMin { get; set; }
        public string? gm_sight_distance_rangeSet { get; set; }
        public string? gm_steering_rangeMax { get; set; }
        public string? gm_steering_rangeMin { get; set; }
        public string? gm_throttle_rangeMax { get; set; }
        public string? gm_throttle_rangeMin { get; set; }
        public string? helicopter_collective_rangeMax { get; set; }
        public string? helicopter_collective_rangeMin { get; set; }
        public string? helicopter_cyclic_pitch_rangeMax { get; set; }
        public string? helicopter_cyclic_pitch_rangeMin { get; set; }
        public string? helicopter_cyclic_roll_rangeMax { get; set; }
        public string? helicopter_cyclic_roll_rangeMin { get; set; }
        public string? helicopter_pedals_rangeMax { get; set; }
        public string? helicopter_pedals_rangeMin { get; set; }
        public string? helicopter_sensor_cue_x_rangeMax { get; set; }
        public string? helicopter_sensor_cue_x_rangeMin { get; set; }
        public string? helicopter_sensor_cue_y_rangeMax { get; set; }
        public string? helicopter_sensor_cue_y_rangeMin { get; set; }
        public string? sensor_cue_x_rangeMax { get; set; }
        public string? sensor_cue_x_rangeMin { get; set; }
        public string? sensor_cue_x_rangeSet { get; set; }
        public string? sensor_cue_y_rangeMax { get; set; }
        public string? sensor_cue_y_rangeMin { get; set; }
        public string? sensor_cue_y_rangeSet { get; set; }
        public string? sensor_cue_z_rangeMax { get; set; }
        public string? sensor_cue_z_rangeMin { get; set; }
        public string? sensor_cue_z_rangeSet { get; set; }
        public string? ship_zoom_rangeMax { get; set; }
        public string? throttle_rangeMax { get; set; }
        public string? throttle_rangeMin { get; set; }
        public string? vtol_rangeMax { get; set; }
        public string? vtol_rangeMin { get; set; }
    }
}
