// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.countermeasures.flares")]
public sealed class FlaresAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FLR";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FLARES");
}

[StreamDeckAction("com.blacksiroghost.wt.countermeasures.ir_proj")]
public sealed class IrProjAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "IRP";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_IR_PROJECTOR");
}

[StreamDeckAction("com.blacksiroghost.wt.countermeasures.smoke")]
public sealed class SmokeAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SMK";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SMOKE_SCREEN");
}
