#requires -Version 5.1
<#
.SYNOPSIS
  Reads tools/spec/modules.psd1 and emits, for every module:
    src/WarThunderStreamDeck.<Asm>/  (csproj, Program.cs, Actions.cs)
    plugin/com.blacksiroghost.wt.<Id>.sdPlugin/  (manifest.json, PI/, Images/)
  Updates WarThunderStreamDeck.sln to reference every project.
  Action types:
    Simple    => generated as a 4-line WarThunderBindingAction subclass
    GearTel   => existing GearAction.cs preserved (custom telemetry behavior)
    FlapsCyc  => existing FlapsAction.cs preserved
    AirbrkTel => existing AirBrakeAction.cs preserved
#>

param([switch]$NoSlnUpdate)

$ErrorActionPreference = 'Stop'
$ProgressPreference    = 'SilentlyContinue'

$repoRoot    = Split-Path -Parent $PSScriptRoot
$srcRoot     = Join-Path $repoRoot 'src'
$pluginsRoot = Join-Path $repoRoot 'plugin'
$slnPath     = Join-Path $repoRoot 'WarThunderStreamDeck.sln'

$specPath = Join-Path $PSScriptRoot 'spec\modules.psd1'
$spec = Import-PowerShellDataFile $specPath
$modules = $spec.Modules

Write-Host "Generating $($modules.Count) module(s) from $specPath" -ForegroundColor Cyan

Add-Type -AssemblyName System.Drawing | Out-Null

$bgDark = [System.Drawing.Color]::FromArgb(40,40,48)

function ConvertTo-Pascal($s) {
    -join ($s -split '[^a-zA-Z0-9]' | Where-Object { $_ } | ForEach-Object {
        $_.Substring(0,1).ToUpper() + $_.Substring(1)
    })
}

function New-KeyImage([string]$path, [int]$size, [string]$label, [int[]]$rgb) {
    $bmp = New-Object System.Drawing.Bitmap($size, $size)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
    $g.Clear($bgDark)
    $accent = [System.Drawing.Color]::FromArgb($rgb[0], $rgb[1], $rgb[2])
    $pad = [int]($size * 0.06)
    $pen = New-Object System.Drawing.Pen($accent, [float][Math]::Max(1, $size/40))
    $g.DrawRectangle($pen, [float]$pad, [float]$pad, [float]($size - 2*$pad), [float]($size - 2*$pad))
    $charW = [Math]::Max(1, $label.Length)
    $fontSize = [int][Math]::Min($size * 0.45, $size * 0.85 / $charW)
    if ($fontSize -lt 6) { $fontSize = 6 }
    $font = New-Object System.Drawing.Font("Segoe UI", [float]$fontSize, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
    $sf = New-Object System.Drawing.StringFormat
    $sf.Alignment = [System.Drawing.StringAlignment]::Center
    $sf.LineAlignment = [System.Drawing.StringAlignment]::Center
    $brush = New-Object System.Drawing.SolidBrush($accent)
    $rect = New-Object System.Drawing.RectangleF([float]0, [float]0, [float]$size, [float]$size)
    $g.DrawString($label, $font, $brush, $rect, $sf)
    $bmp.Save($path, [System.Drawing.Imaging.ImageFormat]::Png)
    $g.Dispose(); $bmp.Dispose(); $font.Dispose(); $pen.Dispose(); $brush.Dispose()
}

function New-MonoIcon([string]$path, [int]$size, [string]$label) {
    $bmp = New-Object System.Drawing.Bitmap($size, $size)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
    $charW = [Math]::Max(1, $label.Length)
    $fontSize = [int][Math]::Min($size * 0.55, $size * 0.95 / $charW)
    if ($fontSize -lt 6) { $fontSize = 6 }
    $font = New-Object System.Drawing.Font("Segoe UI", [float]$fontSize, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
    $sf = New-Object System.Drawing.StringFormat
    $sf.Alignment = [System.Drawing.StringAlignment]::Center
    $sf.LineAlignment = [System.Drawing.StringAlignment]::Center
    $brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White)
    $rect = New-Object System.Drawing.RectangleF([float]0, [float]0, [float]$size, [float]$size)
    $g.DrawString($label, $font, $brush, $rect, $sf)
    $bmp.Save($path, [System.Drawing.Imaging.ImageFormat]::Png)
    $g.Dispose(); $bmp.Dispose(); $font.Dispose(); $brush.Dispose()
}

function Make-CsprojContent($asmName) {
    @"
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WarThunderStreamDeckPlugin</RootNamespace>
    <AssemblyName>WarThunderStreamDeck.$asmName</AssemblyName>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WarThunderStreamDeck.Core\WarThunderStreamDeck.Core.csproj" />
  </ItemGroup>

</Project>
"@
}

function Make-ProgramContent {
    @'
// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
using SharpDeck;

namespace WarThunderStreamDeckPlugin;

internal static class Program
{
    public static Task Main() => StreamDeckPlugin.RunAsync();
}
'@
}

function Make-SimpleActionClass($module, $action) {
    $className = (ConvertTo-Pascal $action.U) + 'Action'
    $bindings = ($action.B | ForEach-Object { '"' + $_ + '"' }) -join ', '
    $uuid = "com.blacksiroghost.wt.$($module.Id).$($action.U)"
    $title = $action.L.Replace('\','\\').Replace('"','\"')
    @"

[StreamDeckAction("$uuid")]
public sealed class $className : WarThunderBindingAction
{
    protected override string TitlePrefix => `"$title`";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, $bindings);
}
"@
}

function Make-ActionsFileContent($module) {
    $actions = $module.Actions | Where-Object { $_.T -eq 'Simple' }
    $body = ($actions | ForEach-Object { Make-SimpleActionClass $module $_ }) -join "`n"
    @"
// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;
$body
"@
}

function Make-ManifestContent($module) {
    $actionEntries = foreach ($a in $module.Actions) {
        $uuid = "com.blacksiroghost.wt.$($module.Id).$($a.U)"
        $tooltip = "Presses your binding for: $($a.B -join ', ')"
        $iconBase = "Images/Actions/$($a.U)"
        $stateImage = if ($a.T -eq 'Simple') { $iconBase } else { "$($iconBase)_0" }

        $stateArr = if ($a.T -eq 'Simple') {
            "[ { `"Image`": `"$iconBase`", `"TitleAlignment`": `"bottom`", `"FontSize`": `"8`" } ]"
        } else {
            "[ { `"Image`": `"$($iconBase)_0`", `"TitleAlignment`": `"bottom`", `"FontSize`": `"8`" }, { `"Image`": `"$($iconBase)_1`", `"TitleAlignment`": `"bottom`", `"FontSize`": `"8`" } ]"
        }

        @"
    {
      "Name": "$($a.N)",
      "UUID": "$uuid",
      "Icon": "$stateImage",
      "Tooltip": "$tooltip",
      "PropertyInspectorPath": "PI/controls.html",
      "States": $stateArr
    }
"@
    }
    $actionsBlock = ($actionEntries -join ",`n")

    @"
{
  "Name": "$($module.Cat)",
  "Version": "0.5.0",
  "Author": "BlackSiroGhost",
  "Description": "$($module.Cat) - War Thunder Stream Deck plugin (auto-generated).",
  "URL": "https://github.com/BlackSiroGhost/WarThunderStreamDeck_Integration",
  "Icon": "Images/Plugin/pluginIcon",
  "Category": "$($module.Cat)",
  "CategoryIcon": "Images/Plugin/categoryIcon",
  "CodePath": "WarThunderStreamDeck.$($module.Asm).exe",
  "CodePathWin": "WarThunderStreamDeck.$($module.Asm).exe",
  "PropertyInspectorPath": "PI/controls.html",
  "SDKVersion": 2,
  "Software": { "MinimumVersion": "6.5" },
  "OS": [{ "Platform": "windows", "MinimumVersion": "10" }],
  "Actions": [
$actionsBlock
  ]
}
"@
}

# Reuse the working PI from mechanisation as the canonical template
$piSourcePath = Join-Path $pluginsRoot 'com.blacksiroghost.wt.mechanisation.sdPlugin\PI\controls.html'
if (-not (Test-Path $piSourcePath)) {
    throw "PI template not found at $piSourcePath"
}
$piTemplate = Get-Content $piSourcePath -Raw

# Reuse existing telemetry-driven icons (gear/flaps/airbrake) and rename to <u>_0/_1 convention
$mechActionImages = Join-Path $pluginsRoot 'com.blacksiroghost.wt.mechanisation.sdPlugin\Images\Actions'
function Copy-StateIcon($module, $action, $existing0, $existing1) {
    $dest = Join-Path $pluginsRoot "com.blacksiroghost.wt.$($module.Id).sdPlugin\Images\Actions"
    if (-not (Test-Path $dest)) { $null = New-Item $dest -ItemType Directory -Force }
    foreach ($pair in @(
        @{ src=$existing0; dst="$($action.U)_0.png" },
        @{ src="$($existing0.Replace('.png','@2x.png'))"; dst="$($action.U)_0@2x.png" },
        @{ src=$existing1; dst="$($action.U)_1.png" },
        @{ src="$($existing1.Replace('.png','@2x.png'))"; dst="$($action.U)_1@2x.png" }
    )) {
        $srcPath = Join-Path $mechActionImages $pair.src
        if (Test-Path $srcPath) {
            Copy-Item $srcPath (Join-Path $dest $pair.dst) -Force
        }
    }
}

# === Main loop ===
$generatedProjects = @()

foreach ($m in $modules) {
    Write-Host ""
    Write-Host "==> $($m.Id)" -ForegroundColor Cyan

    $asm = $m.Asm
    $proj = Join-Path $srcRoot "WarThunderStreamDeck.$asm"
    $pluginDir = Join-Path $pluginsRoot "com.blacksiroghost.wt.$($m.Id).sdPlugin"

    # Wipe regen targets only -- preserve any non-Actions.cs special files
    if (Test-Path $proj) {
        Get-ChildItem $proj -File | Where-Object {
            $_.Name -in @('Actions.cs', 'Program.cs') -or $_.Name -like 'WarThunderStreamDeck.*.csproj'
        } | Remove-Item -Force
    } else {
        $null = New-Item $proj -ItemType Directory -Force
    }

    if (Test-Path $pluginDir) {
        Remove-Item (Join-Path $pluginDir 'manifest.json') -Force -ErrorAction SilentlyContinue
        Remove-Item (Join-Path $pluginDir 'Images') -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item (Join-Path $pluginDir 'PI') -Recurse -Force -ErrorAction SilentlyContinue
    }
    $null = New-Item (Join-Path $pluginDir 'PI') -ItemType Directory -Force
    $null = New-Item (Join-Path $pluginDir 'Images\Plugin') -ItemType Directory -Force
    $null = New-Item (Join-Path $pluginDir 'Images\Actions') -ItemType Directory -Force

    # csproj + Program.cs
    Set-Content (Join-Path $proj "WarThunderStreamDeck.$asm.csproj") (Make-CsprojContent $asm) -Encoding UTF8
    Set-Content (Join-Path $proj 'Program.cs') (Make-ProgramContent) -Encoding UTF8

    # Actions.cs (only Simple actions; specials live in their own files)
    Set-Content (Join-Path $proj 'Actions.cs') (Make-ActionsFileContent $m) -Encoding UTF8

    # manifest.json
    Set-Content (Join-Path $pluginDir 'manifest.json') (Make-ManifestContent $m) -Encoding UTF8

    # PI
    Set-Content (Join-Path $pluginDir 'PI\controls.html') $piTemplate -Encoding UTF8

    # Plugin/category icons (28/56)
    $modLabel = $m.Cat.Substring([Math]::Max(0, $m.Cat.IndexOf('-')+1)).Trim()
    if ($modLabel.Length -eq 0) { $modLabel = $m.Asm }
    $modShort = ($modLabel -replace '[^A-Za-z0-9]', '').Substring(0, [Math]::Min(4, ($modLabel -replace '[^A-Za-z0-9]', '').Length))
    foreach ($s in @(28, 56)) {
        $sfx = if ($s -eq 28) { '' } else { '@2x' }
        New-MonoIcon (Join-Path $pluginDir "Images\Plugin\pluginIcon$sfx.png")   $s $modShort
        New-MonoIcon (Join-Path $pluginDir "Images\Plugin\categoryIcon$sfx.png") $s $modShort
    }

    # Action icons
    foreach ($a in $m.Actions) {
        if ($a.T -eq 'Simple') {
            foreach ($s in @(72, 144)) {
                $sfx = if ($s -eq 72) { '' } else { '@2x' }
                New-KeyImage (Join-Path $pluginDir "Images\Actions\$($a.U)$sfx.png") $s $a.L $m.Accent
            }
        } else {
            # Telemetry-driven: copy state-specific icons from mechanisation source
            switch ($a.T) {
                'GearTel'   { Copy-StateIcon $m $a 'gear_up.png'      'gear_down.png' }
                'FlapsCyc'  { Copy-StateIcon $m $a 'flaps_up.png'     'flaps_down.png' }
                'AirbrkTel' { Copy-StateIcon $m $a 'airbrake_in.png'  'airbrake_out.png' }
            }
        }
    }

    $generatedProjects += "src\WarThunderStreamDeck.$asm\WarThunderStreamDeck.$asm.csproj"
    Write-Host "    csproj, Program.cs, Actions.cs, manifest.json, PI, $($m.Actions.Count) action icons"
}

# Update solution
if (-not $NoSlnUpdate) {
    Write-Host ""
    Write-Host "==> Updating solution..." -ForegroundColor Cyan

    # Drop old projects (we'll re-add)
    $existing = & dotnet sln $slnPath list 2>$null | Where-Object { $_ -like 'src\*' }
    foreach ($e in $existing) {
        & dotnet sln $slnPath remove $e 2>&1 | Out-Null
    }

    # Add Core first, then every module project
    & dotnet sln $slnPath add 'src\WarThunderStreamDeck.Core\WarThunderStreamDeck.Core.csproj' 2>&1 | Out-Null
    foreach ($p in $generatedProjects) {
        & dotnet sln $slnPath add $p 2>&1 | Out-Null
    }
}

Write-Host ""
Write-Host "Generated $($generatedProjects.Count) module(s)." -ForegroundColor Green
Write-Host "Run ./tools/deploy.ps1 to build & install all of them."
