// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.hud.hide_hud")]
public sealed class HideHudAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "HUD";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_HIDE_HUD");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.pause")]
public sealed class PauseAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "PAUS";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_GAME_PAUSE");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.screenshot")]
public sealed class ScreenshotAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SHOT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_SCREENSHOT");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.flightmenu")]
public sealed class FlightmenuAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "MENU";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FLIGHTMENU");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.flightsetup")]
public sealed class FlightsetupAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "STUP";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_FLIGHTMENU_SETUP");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.mp_stat")]
public sealed class MpStatAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "STAT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_MPSTATSCREEN");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.instructor")]
public sealed class InstructorAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "INST";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_INSTRUCTOR");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.ab5")]
public sealed class Ab5Action : WarThunderBindingAction
{
    protected override string TitlePrefix => "AB5";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ACTION_BAR_ITEM_5");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.ab6")]
public sealed class Ab6Action : WarThunderBindingAction
{
    protected override string TitlePrefix => "AB6";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ACTION_BAR_ITEM_6");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.ab7")]
public sealed class Ab7Action : WarThunderBindingAction
{
    protected override string TitlePrefix => "AB7";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ACTION_BAR_ITEM_7");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.ab8")]
public sealed class Ab8Action : WarThunderBindingAction
{
    protected override string TitlePrefix => "AB8";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ACTION_BAR_ITEM_8");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.ab9")]
public sealed class Ab9Action : WarThunderBindingAction
{
    protected override string TitlePrefix => "AB9";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ACTION_BAR_ITEM_9");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.continue")]
public sealed class ContinueAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CONT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_CONTINUE");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.ctrl_mode")]
public sealed class CtrlModeAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "CTRL";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_CONTROL_MODE");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.ctrl_mode_uav")]
public sealed class CtrlModeUavAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "UAV";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_CONTROL_MODE_HUMAN_UAV");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.shot_freq")]
public sealed class ShotFreqAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FREQ";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_CHANGE_SHOT_FREQ");
}

[StreamDeckAction("com.blacksiroghost.wt.hud.exit_cycle")]
public sealed class ExitCycleAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "EXIT";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_EXIT_SHOOTING_CYCLE_MODE");
}
