// AUTO-GENERATED FILE -- regenerated by tools/generate.ps1; do not edit by hand.
namespace WarThunderStreamDeckPlugin.Actions;

using SharpDeck;
using WarThunderStreamDeckPlugin.KeyBindings;
using WarThunderStreamDeckPlugin.Telemetry;

[StreamDeckAction("com.blacksiroghost.wt.tank.sights.rangefinder")]
public sealed class RangefinderAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "RNG";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_RANGEFINDER");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.sights.targ_hold")]
public sealed class TargHoldAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "TARG";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TARGETING_HOLD_GM");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.sights.zoom_hold")]
public sealed class ZoomHoldAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ZMH";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ZOOM_HOLD_GM");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.sights.zoom_toggle")]
public sealed class ZoomToggleAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "ZOOM";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_ZOOM_TOGGLE");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.sights.xhair_light")]
public sealed class XhairLightAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "XHRL";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TOGGLE_GM_CROSSHAIR_LIGHTING");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.sights.tank_nv")]
public sealed class TankNvAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "NV";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TANK_NIGHT_VISION");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.sights.fuse_mode")]
public sealed class FuseModeAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "FUSE";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_TANK_SWITCH_FUSE_MODE");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.sights.thermal")]
public sealed class ThermalAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "THM";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "ID_THERMAL_WHITE_IS_HOT");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.sights.sight_max")]
public sealed class SightMaxAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SD+";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "gm_sight_distance_rangeMax");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.sights.sight_min")]
public sealed class SightMinAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SD-";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "gm_sight_distance_rangeMin");
}

[StreamDeckAction("com.blacksiroghost.wt.tank.sights.sight_set")]
public sealed class SightSetAction : WarThunderBindingAction
{
    protected override string TitlePrefix => "SD=";
    protected override System.Threading.Tasks.Task<TelemetryReading?> ProbeAsync()
        => System.Threading.Tasks.Task.FromResult<TelemetryReading?>(null);
    protected override System.Threading.Tasks.Task OnPressAsync(BindingMap b)
        => TryFireBindingAsync(b, "gm_sight_distance_rangeSet");
}
